Repository redhat-openshift-ecosystem/operator-pipelines, pull requests merged in 2024-12, with the labels that each got.

#752 [ISV-5448] FBC Catalog changes include Operators in the PR Title.
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-hosted-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/set-github-pr-title.yaml
Labels: ok-to-test, ready-for-testing

#754 [ISV-5275] Prepare the integration test framework scaffolding (2/2)
  operator-pipeline-images/operatorcert/integration/testcase.py
  operator-pipeline-images/tests/integration/test_testcase.py
  pdm.lock
  pyproject.toml
Labels: ready-for-testing

#756 update preflight sha for 1.11.1 release
  ansible/roles/operator-pipeline/templates/openshift/tasks/preflight.yml
Labels: lgtm

#758 Skip yamllint for removed bundles
  ansible/roles/operator-pipeline/tasks/operator-pipeline-event-listener.yml
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-ci-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-hosted-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/merge-pr.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/read-config.yaml
  ansible/roles/operator-pipeline/templates/openshift/tasks/yaml-lint.yml
  operator-pipeline-images/operatorcert/parsed_file.py
  operator-pipeline-images/tests/entrypoints/test_detect_changed_operators.py
Labels: ready-for-testing
