Repository redhat-openshift-ecosystem/operator-pipelines, pull requests merged in 2025-05, with the labels that each got.

#818 update preflight sha for 1.13.1 release
  ansible/roles/operator-pipeline/templates/openshift/tasks/preflight.yml
Labels: lgtm, risk/good-to-go

#817 removing skopeo timeout from publish to index task
  ansible/roles/operator-pipeline/templates/openshift/tasks/publish-to-index.yml
Labels: risk/good-to-go

#819 FBC auto-release uses migration option for 4.17+ catalogs
  operator-pipeline-images/operatorcert/entrypoints/add_bundle_to_fbc.py
  operator-pipeline-images/tests/entrypoints/test_add_bundle_to_fbc.py
Labels: ready-for-testing

#821 FBC catalog promotion script supports ci.yaml config
  docs/fbc-catalog-promotion.md
  docs/users/operator-ci-yaml.md
  mkdocs.yml
  operator-pipeline-images/operatorcert/entrypoints/check_permissions.py
  operator-pipeline-images/tests/entrypoints/test_check_permissions.py
  scripts/promote-catalog.py
Labels: ready-for-testing

#820 Add static test for catalog olm.bundle.object presence
  docs/users/static_checks.md
  fbc/Makefile
  operator-pipeline-images/operatorcert/entrypoints/add_bundle_to_fbc.py
  operator-pipeline-images/operatorcert/operator_repo/core.py
  operator-pipeline-images/operatorcert/static_tests/common/operator_catalogs.py
  operator-pipeline-images/operatorcert/utils.py
  operator-pipeline-images/tests/entrypoints/test_add_bundle_to_fbc.py
  operator-pipeline-images/tests/operator_repo/test_operator_catalog.py
  operator-pipeline-images/tests/static_tests/common/test_operator_catalogs.py
  operator-pipeline-images/tests/test_utils.py
Labels: ready-for-testing

#822 [ISV-5925] bot commits are signed off
  ansible/roles/operator-pipeline/templates/openshift/tasks/add-bundle-to-fbc.yml
Labels: risk/good-to-go, ready-for-testing

#823 [ISV-5939] replace generate-index task
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-ci-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-hosted-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/build-fbc-scratch-catalog.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/buildah.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/generate-index.yml
Labels: ready-for-testing
