Repository redhat-openshift-ecosystem/operator-pipelines, pull requests merged in 2025-04, with the labels that each got.

#809 Update preflight SHA for 1.13.0 release
  ansible/roles/operator-pipeline/templates/openshift/tasks/preflight.yml
Labels: lgtm

#810 [ISV-5825] trigger hosted pipeline when PR is marked as ready
  ansible/roles/operator-pipeline/tasks/community-pipeline-event-listener.yml
  ansible/roles/operator-pipeline/tasks/operator-pipeline-event-listener.yml
Labels: risk/good-to-go, ready-for-testing

#807 Sort parsed output for consistent data representation
  ansible/roles/operator-pipeline/templates/openshift/tasks/publish-to-index.yml
  operator-pipeline-images/operatorcert/parsed_file.py
  operator-pipeline-images/operatorcert/utils.py
  operator-pipeline-images/tests/test_parsed_file.py
Labels: ready-for-testing

#806 [ISV-5776] Add "how to remove operator from catalog" to docs.
  docs/README.md
Labels: risk/good-to-go
