Repository redhat-openshift-ecosystem/operator-pipelines, pull requests merged in 2025-02, with the labels that each got.

#773 ISV-5501: Validate release-config.yaml with json schema - added json …
  operator-pipeline-images/operatorcert/schemas/release-config-schema.json
  operator-pipeline-images/operatorcert/static_tests/common/bundle.py
  operator-pipeline-images/tests/static_tests/common/test_bundle.py
Labels: ready-for-testing

#778 ISV-5501: Validate release-config.yaml with json schema - update bund…
  operator-pipeline-images/operatorcert/static_tests/common/bundle.py
  operator-pipeline-images/tests/static_tests/common/test_bundle.py
Labels: ready-for-testing

#774 Auto-release bundle to FBC
  ansible/inventory/group_vars/operator-pipeline-prod.yml
  ansible/inventory/group_vars/operator-pipeline.yml
  ansible/roles/operator-pipeline/tasks/community-hosted-pipeline-trigger.yml
  ansible/roles/operator-pipeline/tasks/community-release-pipeline-trigger.yml
  ansible/roles/operator-pipeline/tasks/operator-hosted-pipeline-trigger.yml
  ansible/roles/operator-pipeline/tasks/operator-release-pipeline-trigger.yml
  ansible/roles/operator-pipeline/tasks/pipeline-secrets.yml
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-hosted-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-release-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/add-bundle-to-fbc.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/merge-pr.yml
  ansible/vaults/common/github-bot-ssh
  ansible/vaults/prod/github-bot-ssh
Labels: ready-for-testing

#784 Bump cryptography package
  pdm.lock
Labels: risk/good-to-go, ready-for-testing

#787 Add catalog mapping validation
  docs/users/static_checks.md
  operator-pipeline-images/operatorcert/schemas/ci-schema.json
  operator-pipeline-images/operatorcert/schemas/release-config-schema.json
  operator-pipeline-images/operatorcert/static_tests/common/operator.py
  operator-pipeline-images/tests/static_tests/common/test_bundle.py
  operator-pipeline-images/tests/static_tests/common/test_operator.py
  pdm.lock
  pyproject.toml
Labels: ready-for-testing

#788 [ISV-5618] Fix check_upgrade_graph_loop for community operators
  operator-pipeline-images/operatorcert/static_tests/community/bundle.py
  operator-pipeline-images/operatorcert/static_tests/community/operator.py
  operator-pipeline-images/operatorcert/static_tests/helpers.py
  operator-pipeline-images/tests/static_tests/community/test_bundle.py
  operator-pipeline-images/tests/static_tests/community/test_operator.py
  operator-pipeline-images/tests/static_tests/test_helpers.py
Labels: ready-for-testing

#772 [ISV-5276] Create helper functions for GitHub branches for copy and delete operations.
  operator-pipeline-images/operatorcert/github.py
  operator-pipeline-images/tests/test_github.py
Labels: risk/good-to-go

#790 Link catalog PR in summary comment
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-hosted-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/pipelines/operator-release-pipeline.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/add-bundle-to-fbc.yml
  ansible/roles/operator-pipeline/templates/openshift/tasks/github-pipelinerun-summary.yml
Labels: ready-for-testing

#795 enabling 4.18 clusters to be used in hosted pipeline
  ansible/roles/operator-pipeline/templates/openshift/tasks/preflight-trigger.yml
Labels: risk/good-to-go, ready-for-testing
